### PR TITLE
Reset pending queue before IOStream write begins

### PR DESCRIPTION
**Pull request by theisensanders-wf**
**Problem:**
When a command is queued up while the coroutine to write to the socket is running, the queued command will be lost when the write finishes and `self._pending` is set to an empty list

**Solution:**
Reset the pending queue BEFORE the write

Side note: In order to still maintain the queue on an error like before, I save it off in a tmp variable that gets restored if an iostream exception is raised

### CODE REVIEW

**Comment by brianshannan-wf** [comment]
+1

**Comment by theisensanders-wf** [comment]
@tylertreat @wallyqs

**Comment by wallyqs** [comment]
Thanks for the contribution! Just one small question:
`When a command is queued up while the coroutine to write to the socket is running`
Is there a sample maybe of reproducing this issue? If using the same thread/event loop then only one coroutine would be able to buffer pending data or doing the flush here no?

**Comment by theisensanders-wf** [comment]
I am using a single thread/event loop and able to reliably reproduce when publishing large payloads. 

My understanding of tornado iostreams is minimal, but it looks like the write is an async operation so it could be placed after the call to queue up a new command in the event loop.

**Comment by tylertreat** [comment]
@theisensanders-wf any chance you can repro in a unit test?

**Comment by theisensanders-wf** [comment]
@tylertreat @wallyqs I added a test unit test that will fail on master some of the time. I couldn't figure out how to create a test that repro'd it 100% of the time but with my change this test should fail 0% of the time.

**Comment by wallyqs** [comment]
I confirmed the issue so including this patch as is for now since it fixes the problem.  I'm updating the test in this branch (https://github.com/wallyqs/python-nats/commits/flusher-race-cond-fixes) where I can always reproduce the issue and also found out found another problem with the `flush` API which similarly drops the commands when doing the write in some cases.

**Comment by tylertreat** [comment]
@wallyqs seems like it might be worth cutting a new patch release with these fixes. What do you think?

**Comment by wallyqs** [comment]
definitely, I will release a new version today. @theisensanders-wf Thanks a lot for the investigation and the fix for this issue!

**Comment by wallyqs** [comment]
Released v0.5.4 of the client in pypi https://github.com/nats-io/python-nats/releases/tag/v0.5.4
Thanks again!

**Pull request merged**
